language: node_js
branches:
  only:
  - master
  - /feature/.*$/
 
node_js:
  - 10

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules
    
before_install:    
    - docker pull selenium/node-chrome:latest
    - docker pull selenium/hub:latest
    - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:latest
    - docker run -d --link selenium-hub:hub --name selenium-node-chrome -v /dev/shm:/dev/shm selenium/node-chrome:latest

script:
  - yarn test